allow-lan: false
dns:
  cache-algorithm: arc
  default-nameserver: &id001
  - 114.114.114.114
  - 119.29.29.29
  - 211.136.17.107
  - 211.136.20.203
  - 211.137.58.20
  - 211.137.64.163
  - 223.5.5.5
  direct-nameserver: *id001
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - geosite:gfw,tld-!cn,geolocation-!cn
  - rule-set:proxy,myProxy
  fake-ip-filter-mode: whitelist
  fallback: &id002
  - https://1.1.1.1/dns-query#DNS
  - https://8.8.8.8/dns-query#DNS
  - https://9.9.9.9/dns-query#DNS
  - https://185.222.222.222/dns-query#DNS
  - https://208.67.222.222/dns-query#DNS
  fallback-filter:
    geoip: true
    geoip-code: CN
  ipv6: true
  listen: 0.0.0.0:53
  nameserver: *id001
  nameserver-policy:
    geosite:cn,connectivity-check,private: *id001
    geosite:gfw,tld-!cn,geolocation-!cn: *id002
    rule-set:direct,myDirect: *id001
    rule-set:proxy,myProxy: *id002
  prefer-h3: false
  proxy-server-nameserver: *id001
  respect-rules: true
  use-hosts: false
  use-system-hosts: false
external-controller-cors:
  allow-origins:
  - '*'
  allow-private-network: true
geo-auto-update: true
geo-update-interval: 12
geodata-loader: standard
geodata-mode: true
geox-url:
  asn: https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
  geoip: https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
  geosite: https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
  mmdb: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb
ipv6: true
log-level: error
mixed-port: 7890
mode: rule
myDirectDNS: *id001
myProxyDNS: *id002
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- name: vpnshield
  port: 80
  server: 162.159.250.246
  type: vless
  network: ws
  udp: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      host: vpnshield5554.vpnvpnfree5.workers.dev
  uuid: 63583ca2-b618-4bd8-96a1-08febe3a6730
  client-fingerprint: chrome
- {name: US_speednode_0120, server: 135.84.79.177, port: 8880, type: vless, uuid: 583ceab3-4022-4553-9158-9bedc625ad4e, tls: false, skip-cert-verify: false, servername: ip.langmanshanxi.top, network: ws, ws-opts: {path: "/TELEGRAM-v2ray_configs_pools_v2ray_configs_pools_v2ray_configs_pools?ed=512", headers: {Host: ip.langmanshanxi.top}}, udp: true}
- name: ç¾å›½-18
  alterId: 0
  network: ws
  port: 8880
  server: 135.84.75.3
  servername: Telegram-channel-v2ray_configs_pools
  skip-cert-verify: false
  tls: false
  type: vless
  udp: true
  uuid: b5441b0d-2147-4898-8a6a-9b2c87f58382
  ws-opts:
    headers:
      Host: bitget1.asdasd.click
    path: /TelegramğŸ‡¨ğŸ‡³
- name: ç¾å›½-9
  alterId: 0
  network: ws
  port: '8880'
  server: 63.141.128.177
  skip-cert-verify: false
  type: vless
  uuid: 583ceab3-4022-4553-9158-9bedc625ad4e
  ws-opts:
    headers:
      Host: ip.langmanshanxi.top
    path: /TelegramğŸ‡¨ğŸ‡³ @WangCai2 /?ed=2560
- name: ç¾å›½-11
  alterId: 0
  network: ws
  port: '8880'
  server: 130.250.137.3
  servername: Telegram-channel-WangCai2
  skip-cert-verify: false
  type: vless
  uuid: b5441b0d-2147-4898-8a6a-9b2c87f58382
  ws-opts:
    headers:
      Host: bitget1.asdasd.click
    path: /TelegramğŸ‡¨ğŸ‡³
- name: ç¾å›½-7
  alterId: 0
  network: ws
  port: 8880
  server: 135.84.79.177
  servername: ip.langmanshanxi.top
  skip-cert-verify: false
  tls: false
  type: vless
  udp: true
  uuid: 583ceab3-4022-4553-9158-9bedc625ad4e
  ws-opts:
    headers:
      Host: ip.langmanshanxi.top
    path: /TELEGRAM-MARAMBASHI_MARAMBASHI_MARAMBASHI?ed=512
- name: ç¾å›½-21
  alterId: 0
  network: ws
  port: 8880
  server: 199.34.229.177
  servername: Telegram-channel-WangCai2
  skip-cert-verify: false
  tls: false
  type: vless
  udp: true
  uuid: 583ceab3-4022-4553-9158-9bedc625ad4e
  ws-opts:
    headers:
      Host: ip.langmanshanxi.top
    path: /TelegramğŸ‡¨ğŸ‡³
- name: ç¾å›½-14
  alterId: 0
  network: ws
  port: '8880'
  server: 141.193.213.177
  skip-cert-verify: false
  type: vless
  uuid: 583ceab3-4022-4553-9158-9bedc625ad4e
  ws-opts:
    headers:
      Host: ip.langmanshanxi.top
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
- name: æ—¥æœ¬-14
  alterId: 0
  network: ws
  port: '8880'
  server: 91.193.58.1
  servername: kjgx.laoyoutiao.link
  tls: false
  type: vless
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  ws-opts:
    headers:
      Host: kjgx.laoyoutiao.link
    path: /Telegram @WangCai2 /?ed=2560
- name: æ—¥æœ¬-37
  alterId: 0
  network: ws
  port: 8880
  server: 91.193.58.248
  servername: sk.laoyoutiao.link
  skip-cert-verify: false
  tls: false
  type: vless
  udp: true
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  ws-opts:
    headers:
      Host: sk.laoyoutiao.link
    path: /TelegramU0001F1E8U0001F1F3?ed=2048
- name: æ—¥æœ¬-1
  alterId: 0
  network: ws
  port: 8880
  server: 91.193.58.54
  servername: kjgx.laoyoutiao.link
  skip-cert-verify: false
  tls: false
  type: vless
  udp: true
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  ws-opts:
    headers:
      Host: kjgx.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2560
proxy-groups:
- name: ç›´è¿è§„åˆ™
  proxies:
  - DIRECT
  - å…¨çƒäº’è”
  type: select
- name: æ¼ç½‘ä¹‹é±¼
  proxies:
  - DIRECT
  - å…¨çƒäº’è”
  type: select
- name: å…¨çƒäº’è”
  proxies:
  - å…±äº«èŠ‚ç‚¹
  - ç§æœ‰èŠ‚ç‚¹
  - DIRECT
  type: select
- name: ç§æœ‰èŠ‚ç‚¹
  type: select
  use:
  - æˆ‘çš„æœºåœº
- name: å…±äº«èŠ‚ç‚¹
  proxies:
  - å…±äº«èŠ‚ç‚¹-å»¶è¿Ÿæœ€ä½
  - å…±äº«èŠ‚ç‚¹-æ•…éšœè½¬ç§»
  - å…±äº«èŠ‚ç‚¹-è´Ÿè½½å‡è¡¡
  - å…±äº«èŠ‚ç‚¹-æ‰‹åŠ¨é€‰æ‹©
  - DIRECT
  type: select
- name: MYPROXY
  proxies:
  - å…±äº«èŠ‚ç‚¹
  - ç§æœ‰èŠ‚ç‚¹
  - DIRECT
  type: select
- name: TWITTER
  proxies:
  - å…±äº«èŠ‚ç‚¹
  - ç§æœ‰èŠ‚ç‚¹
  - DIRECT
  type: select
- name: YOUTUBE
  proxies:
  - å…±äº«èŠ‚ç‚¹
  - ç§æœ‰èŠ‚ç‚¹
  - DIRECT
  type: select
- name: GITHUB
  proxies:
  - å…±äº«èŠ‚ç‚¹
  - ç§æœ‰èŠ‚ç‚¹
  - DIRECT
  type: select
- name: TELEGRAM
  proxies:
  - å…±äº«èŠ‚ç‚¹
  - ç§æœ‰èŠ‚ç‚¹
  - DIRECT
  type: select
- name: AI
  proxies:
  - å…±äº«èŠ‚ç‚¹
  - ç§æœ‰èŠ‚ç‚¹
  - DIRECT
  type: select
- name: GAME
  proxies:
  - å…±äº«èŠ‚ç‚¹
  - ç§æœ‰èŠ‚ç‚¹
  - DIRECT
  type: select
- name: FORUMS
  proxies:
  - å…±äº«èŠ‚ç‚¹
  - ç§æœ‰èŠ‚ç‚¹
  - DIRECT
  type: select
- name: ENTERTAINMENT
  proxies:
  - å…±äº«èŠ‚ç‚¹
  - ç§æœ‰èŠ‚ç‚¹
  - DIRECT
  type: select
- name: GFW
  proxies:
  - å…±äº«èŠ‚ç‚¹
  - ç§æœ‰èŠ‚ç‚¹
  - DIRECT
  type: select
- name: GEOLOCATON-!CN
  proxies:
  - å…±äº«èŠ‚ç‚¹
  - ç§æœ‰èŠ‚ç‚¹
  - DIRECT
  type: select
- name: TLD-!CN
  proxies:
  - å…±äº«èŠ‚ç‚¹
  - ç§æœ‰èŠ‚ç‚¹
  - DIRECT
  type: select
- name: PROXY
  proxies:
  - å…±äº«èŠ‚ç‚¹
  - ç§æœ‰èŠ‚ç‚¹
  - DIRECT
  type: select
- name: DNS
  proxies:
  - å…±äº«èŠ‚ç‚¹
  - ç§æœ‰èŠ‚ç‚¹
  - DIRECT
  type: select
- interval: 360
  name: å…±äº«èŠ‚ç‚¹-å»¶è¿Ÿæœ€ä½
  proxies: &id003
  - vpnshield
  - US_speednode_0120
  - ç¾å›½-18
  - ç¾å›½-9
  - ç¾å›½-11
  - ç¾å›½-7
  - ç¾å›½-21
  - ç¾å›½-14
  - æ—¥æœ¬-14
  - æ—¥æœ¬-37
  - æ—¥æœ¬-1
  type: url-test
  url: https://www.youtube.com/generate_204
- interval: 360
  name: å…±äº«èŠ‚ç‚¹-æ•…éšœè½¬ç§»
  proxies: *id003
  type: fallback
  url: https://www.youtube.com/generate_204
- interval: 360
  name: å…±äº«èŠ‚ç‚¹-è´Ÿè½½å‡è¡¡
  proxies: *id003
  type: load-balance
  url: https://www.youtube.com/generate_204
- name: å…±äº«èŠ‚ç‚¹-æ‰‹åŠ¨é€‰æ‹©
  proxies: *id003
  type: select
proxy-providers:
  æˆ‘çš„æœºåœº:
    health-check:
      enable: true
      expected-status: 204
      interval: 14400
      lazy: true
      timeout: 5000
      url: https://www.youtube.com/generate_204
    interval: 86400
    path: ./myOwn.yaml
    type: file
rule-providers:
  apple:
    behavior: domain
    interval: 14400
    path: ./ruleset/apple.txt
    type: http
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt
  direct:
    behavior: domain
    interval: 14400
    path: ./ruleset/direct.txt
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
  icloud:
    behavior: domain
    interval: 14400
    path: ./ruleset/icloud.txt
    type: http
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt
  myDirect:
    behavior: domain
    interval: 3600
    path: ./ruleset/myDirect.txt
    type: file
  myProxy:
    behavior: domain
    interval: 3600
    path: ./ruleset/myProxy.txt
    type: file
  proxy:
    behavior: domain
    interval: 14400
    path: ./ruleset/proxy.txt
    type: http
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt
rules:
- RULE-SET,myProxy,MYPROXY
- RULE-SET,myDirect,ç›´è¿è§„åˆ™
- RULE-SET,direct,ç›´è¿è§„åˆ™
- GEOSITE,category-ads-all,REJECT
- GEOSITE,cn,ç›´è¿è§„åˆ™
- GEOSITE,connectivity-check,ç›´è¿è§„åˆ™
- RULE-SET,apple,ç›´è¿è§„åˆ™
- RULE-SET,icloud,ç›´è¿è§„åˆ™
- GEOSITE,private,ç›´è¿è§„åˆ™
- GEOSITE,category-speedtest@cn,ç›´è¿è§„åˆ™
- GEOIP,CN,ç›´è¿è§„åˆ™,no-resolve
- GEOSITE,twitter,TWITTER
- GEOSITE,youtube,YOUTUBE
- GEOSITE,github,GITHUB
- GEOSITE,telegram,TELEGRAM
- GEOSITE,category-ai-!cn,AI
- GEOSITE,category-games-!cn,GAME
- GEOSITE,category-forums,FORUMS
- GEOSITE,category-entertainment,ENTERTAINMENT
- GEOSITE,gfw,GFW
- GEOSITE,geolocation-!cn,GEOLOCATON-!CN
- GEOSITE,tld-!cn,TLD-!CN
- GEOIP,telegram,TELEGRAM,no-resolve
- GEOIP,twitter,TWITTER,no-resolve
- RULE-SET,proxy,PROXY
- MATCH,æ¼ç½‘ä¹‹é±¼
sniffer:
  enable: false
  force-dns-mapping: true
  force-domain:
  - +.v2ex.com
  override-destination: false
  parse-pure-ip: true
  skip-domain:
  - Mijia Cloud
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  device: Mihomo
  dns-hijack:
  - any:53
  - tcp://any:53
  enable: true
  mtu: 1500
  stack: mixed
  strict-route: true
unified-delay: false
